version: "{build}"

platform:
  - Win32
  - x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - msvc: 'Visual Studio 12 2013'
    - msvc: 'Visual Studio 14 2015'

configuration:
  - Debug
  - Release

init:
  - ps: Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
  - cmd: xmake --version
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\sv

branches:
  only:
    - master
    - dev

install:
  - git submodule update --init --recursive

before_build:
  - cmd: cd C:\projects\sv
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=%msvc%
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=%msvc% Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: C:\projects\sv\build\sv.sln
  verbosity: quiet

build_script:
  - ps: cd C:\projects\sv
  - cmd: if %platform%==x64 xmake f -a x64
  - cmd: if %configuration%==Debug xmake f -m debug
  - cmd: if %configuration%==Release xmake f -m release
  - cmd: xmake -v -a

test_script:
  - ps: cd C:\projects\sv\build
  - cmd: ctest -VV
  - ps: cd C:\projects\sv
  - cmd: xmake check
